import { useMemo, useState } from 'react'
import { AlertTriangle, ArrowLeft, Check, Copy, FileText, Mail, MessageCircle, Paperclip, ShieldAlert } from 'lucide-react'
import { PLANEJAMENTO_CC_STRING, PLANEJAMENTO_TO } from '../components/EmailRecipients'
const orientationText = `Bom dia, Professor(a) [NOME].

Para dar continuidade ao processo de mudança de endereço e reinstalação dos equipamentos, mesmo quando a mudança ocorrer para um prédio contíguo, é necessário encaminhar um ofício da SEMED, devidamente assinado e destinado ao setor de Planejamento do projeto.

O ofício deverá ser enviado para o e-mail:

planejamento@eace.org.br

Com cópia para:

suporte@eace.org.br; martino.cardoso@gtsnet.com.br; douglas.bicudo@eace.org.br; cristiano.sousa@gtsnet.com.br

Para facilitar a análise e agilizar o atendimento, pedimos que o ofício contenha as seguintes informações:

• Nome e INEP da escola;
• Endereço antigo da unidade;
• Novo endereço completo, com CEP;
• Latitude e Longitude do novo endereço;
• Croqui ou planta baixa da nova escola, informando também se houve ampliação do número de salas de aula;
• Informação sobre a permanência dos equipamentos no endereço antigo;
• Informação sobre a existência de energia elétrica instalada no novo endereço.

Após preparar o ofício, realize o envio para os e-mails informados acima e, por gentileza, nos informe quando o envio for realizado para que possamos acompanhar o processo.

Pedimos também que, assim que o ofício estiver disponível, nos encaminhe uma cópia pelo WhatsApp, para que possamos realizar a solicitação por nossa parte.

Ficamos à disposição e aguardamos a confirmação do envio.`

const initialData = { escola: '', inep: '', local: '', endereco: '', contato: '', latitude: '', longitude: '', fixa: '' }
const cc = PLANEJAMENTO_CC_STRING

export function MudancaEndereco({ onBack }) {
  const [stage, setStage] = useState(1)
  const [confirmed, setConfirmed] = useState(true)
  const [answers, setAnswers] = useState({ antigo: '', energia: '', salas: '' })
  const [orientationConfirmed, setOrientationConfirmed] = useState(false)
  const [copied, setCopied] = useState('')
  const [data, setData] = useState(initialData)
  const emailSubject = `MUDANÇA DE ENDEREÇO - ${data.escola || '[ESCOLA]'} - ${data.inep || '[INEP]'}`
  const emailBody = useMemo(() => `Prezados,\n\nEm contato com a gestão da unidade escolar, fomos informados que a ${data.escola || '[ESCOLA]'} - INEP: ${data.inep || '[INEP]'} mudou de endereço e encontra-se atualmente no endereço informado abaixo.\n\nDessa forma, será necessária a remoção dos equipamentos instalados no endereço anterior e a reinstalação no novo endereço.\n\nDados do novo endereço:\n\nINEP: ${data.inep}\n\nEscola: ${data.escola}\n\nLocal: ${data.local}\n\nEndereço: ${data.endereco}\n\nContato: ${data.contato}\n\nLatitude: ${data.latitude}\n\nLongitude: ${data.longitude}\n\nLocalização fixa: ${data.fixa}\n\nInformações adicionais:\n\nOs equipamentos permanecem instalados no endereço antigo, correspondente à unidade desativada.\n\nO novo endereço já possui energia elétrica instalada, estando apto para receber os equipamentos.\n\nAs evidências do novo endereço e a planta baixa seguem anexadas para validação.\n\nAdicionalmente, informamos que o responsável pela unidade escolar foi devidamente orientado a encaminhar ofício ao setor de Planejamento, formalizando a mudança de endereço e solicitando a reinstalação dos equipamentos no novo local, conforme o procedimento estabelecido.\n\nFicamos à disposição para quaisquer esclarecimentos.`, [data])
  const copy = async (value, key) => { await navigator.clipboard.writeText(value); setCopied(key); window.setTimeout(() => setCopied(''), 2200) }
  const selectStage = (value) => { setStage(value); window.setTimeout(() => document.getElementById(`etapa-mudanca-endereco-${value}`)?.scrollIntoView({ behavior: 'smooth', block: 'start' }), 0) }
  const updateData = (field, value) => setData((current) => ({ ...current, [field]: value }))
  const updateAnswer = (field, value) => setAnswers((current) => ({ ...current, [field]: value }))
  const fullEmail = `Para: ${PLANEJAMENTO_TO}\nCC: ${PLANEJAMENTO_CC_STRING}\nAssunto: ${emailSubject}\n\n${emailBody}`

  if (!confirmed) return <div className="address-flow"><BackButton onClick={onBack} /><AddressHeader /><div className="address-stop"><AlertTriangle size={24} /><h2>A mudança de endereço não foi confirmada.</h2><p>Não seguir para este procedimento.</p><button onClick={() => setConfirmed(true)}>VOLTAR À DECISÃO</button></div></div>

  return <div className="address-flow"><BackButton onClick={onBack} /><AddressHeader /><AddressStepper stage={stage} onStage={selectStage} /><div className="address-now"><span><i /> EM ANDAMENTO</span><strong>{stage === 1 ? 'Confirmar mudança de endereço' : stage === 2 ? 'Levantar informações da mudança' : stage === 3 ? 'Orientar responsável e solicitar ofício' : 'Solicitação por e-mail'}</strong><button onClick={() => selectStage(Math.min(4, stage + 1))}>Próxima etapa <ArrowLeft size={14} /></button></div>
    <section id="etapa-mudanca-endereco-1" className="address-section"><AddressTitle number="01" title="Confirmar mudança de endereço" description="Confirmar com o(a) responsável pela escola se a unidade realmente realizou ou realizará uma mudança de endereço." /><div className="address-card"><CardHeading icon={<MessageCircle size={13} />} label="CONFIRMAÇÃO COM A RESPONSÁVEL" /><p>Confirmar com o(a) responsável pela escola se a unidade está em processo de mudança de endereço.</p><CopyButton label="COPIAR PERGUNTA" copied={copied === 'q1'} onClick={() => copy('A escola mudou ou irá mudar de endereço?', 'q1')} /></div><div className="address-decision"><strong>A escola confirmou a mudança de endereço?</strong><div><button className="selected" onClick={() => setConfirmed(true)}><Check size={14} /> SIM — MUDANÇA CONFIRMADA</button><button onClick={() => setConfirmed(false)}>NÃO — MUDANÇA NÃO CONFIRMADA</button></div></div></section>
    <section id="etapa-mudanca-endereco-2" className="address-section"><AddressTitle number="02" title="Levantamento das informações" description="Após confirmar a mudança de endereço, levantar com o(a) responsável as informações necessárias para entender a situação do endereço antigo e do novo local." /><div className="question-grid"><QuestionCard title="Equipamentos no endereço antigo" question="Os equipamentos permanecem instalados no endereço antigo?" value={answers.antigo} onChange={(value) => updateAnswer('antigo', value)} /><QuestionCard title="Energia elétrica no novo endereço" question="O novo endereço já possui energia elétrica instalada?" value={answers.energia} onChange={(value) => updateAnswer('energia', value)} /><QuestionCard title="Ampliação de salas" question="Houve ampliação do número de salas de aula no novo endereço?" value={answers.salas} onChange={(value) => updateAnswer('salas', value)} /></div><div className="address-evidence"><FileText size={18} /><div><h3>EVIDÊNCIAS DO NOVO ENDEREÇO</h3><p>Coletar com o(a) responsável fotos do novo endereço e o croqui/planta baixa da nova unidade.</p><strong>Devem ser coletadas fotos do novo local e o croqui/planta baixa.</strong><span>Esses materiais serão utilizados posteriormente na solicitação.</span></div></div><div className="address-summary"><h3>INFORMAÇÕES LEVANTADAS</h3><SummaryItem label="Equipamentos no endereço antigo" value={answers.antigo || 'Aguardando informação'} /><SummaryItem label="Energia elétrica no novo endereço" value={answers.energia || 'Aguardando informação'} /><SummaryItem label="Houve ampliação de salas" value={answers.salas || 'Aguardando informação'} /><SummaryItem label="Fotos do novo endereço" value="Devem ser coletadas" /><SummaryItem label="Croqui/planta baixa" value="Deve ser obtido" /></div></section>
    <section id="etapa-mudanca-endereco-3" className="address-section"><AddressTitle number="03" title="Orientação à responsável" description="Orientar a responsável sobre o envio do ofício ao setor de Planejamento." /><div className="address-card address-orientation"><CardHeading icon={<MessageCircle size={13} />} label="COMUNICAÇÃO OFICIAL" title="ORIENTAÇÃO À RESPONSÁVEL — OFÍCIO DE MUDANÇA DE ENDEREÇO" /><pre>{orientationText}</pre><CopyButton label="COPIAR ORIENTAÇÃO" copied={copied === 'orientation'} onClick={() => copy(orientationText, 'orientation')} /></div><div className="address-card"><CardHeading icon={<ShieldAlert size={13} />} label="CONFIRMAÇÃO DA ORIENTAÇÃO" title="CONFIRMAÇÃO DA ORIENTAÇÃO" /><p>Após enviar a orientação, solicitar à responsável a confirmação do recebimento.</p><div className="address-question"><strong>Confirma o recebimento da orientação?</strong><CopyButton label="COPIAR PERGUNTA" copied={copied === 'q2'} onClick={() => copy('Confirma o recebimento da orientação?', 'q2')} /></div><button className="address-confirm" onClick={() => setOrientationConfirmed(true)}>{orientationConfirmed ? <><Check size={14} /> ✓ Responsável confirmou o recebimento da orientação.</> : 'PENDENTE — MARCAR COMO CONFIRMADO'}</button></div><div className="address-card address-evidence-note"><CardHeading icon={<FileText size={13} />} label="REGISTRO EXTERNO" title="EVIDÊNCIA DA ORIENTAÇÃO" /><p>Guardar no chamado o print da conversa demonstrando que a responsável recebeu e foi devidamente orientada sobre o procedimento.</p></div><div className="address-waiting"><Paperclip size={17} /><div><strong>AGUARDAR CÓPIA DO OFÍCIO</strong><p>Assim que a responsável conseguir o ofício, solicitar que ela encaminhe uma cópia para nossa equipe pelo WhatsApp.</p><span>A cópia do ofício será utilizada para realizar a solicitação por nossa parte na Etapa 4.</span></div></div></section>
    <section id="etapa-mudanca-endereco-4" className="address-section"><AddressTitle number="04" title="Solicitação ao Planejamento" description="Após conseguir o ofício com a responsável, realizar a solicitação por e-mail." /><AddressEmail data={data} updateData={updateData} emailSubject={emailSubject} emailBody={emailBody} fullEmail={fullEmail} copied={copied} copy={copy} /></section>
  </div>
}

function BackButton({ onClick }) { return <button className="back-button" onClick={onClick}><ArrowLeft size={16} /> Voltar para paralisados</button> }
function AddressHeader() { return <div className="address-heading"><span className="eyebrow">Procedimento operacional</span><h1>Mudança de Endereço</h1><p>Procedimento para confirmação da mudança, levantamento das condições do novo local e solicitação de reinstalação dos equipamentos.</p></div> }
function AddressStepper({ stage, onStage }) { const items = ['Confirmar mudança', 'Levantar informações', 'Orientar responsável', 'Solicitar ao Planejamento']; return <div className="address-stepper">{items.map((item, index) => <button className={stage === index + 1 ? 'active' : stage > index + 1 ? 'done' : ''} onClick={() => onStage(index + 1)} key={item}><span>{stage > index + 1 ? <Check size={14} /> : `0${index + 1}`}</span><small>ETAPA {index + 1}</small><strong>{item}</strong></button>)}</div> }
function AddressTitle({ number, title, description }) { return <div className="address-title"><span>{number}</span><div><em>PASSO {number}</em><h2>ETAPA {Number(number)} — {title}</h2><p>{description}</p></div></div> }
function CardHeading({ icon, label, title }) { return <div className="address-card-heading"><span className="address-label">{icon} {label}</span>{title && <h2>{title}</h2>}</div> }
function CopyButton({ label, copied, onClick }) { return <button className={`address-copy ${copied ? 'copied' : ''}`} onClick={onClick}><Copy size={14} /> {copied ? '✓ Orientação copiada!' : label}</button> }
function QuestionCard({ title, question, value, onChange }) { return <div className="question-card"><span className="address-label">LEVANTAMENTO</span><h3>{title}</h3><p>{question}</p><div>{['Sim', 'Não'].map((option) => <button className={value === option ? 'selected' : ''} onClick={() => onChange(option)} key={option}>{value === option && <Check size={13} />} {option}</button>)}</div></div> }
function SummaryItem({ label, value }) { return <div><span>{label}</span><strong>{value}</strong></div> }
function AddressEmail({ data, updateData, emailSubject, emailBody, fullEmail, copied, copy }) { const fields = [['escola', 'Escola'], ['inep', 'INEP'], ['local', 'Local'], ['endereco', 'Endereço'], ['contato', 'Contato'], ['latitude', 'Latitude'], ['longitude', 'Longitude'], ['fixa', 'Localização fixa']]; return <div className="address-email"><div className="address-card"><CardHeading icon={<FileText size={13} />} label="PREENCHIMENTO" title="Dados do novo endereço" /><div className="address-form">{fields.map(([field, label]) => <label key={field}><span>{label}</span><input value={data[field]} onChange={(event) => updateData(field, event.target.value)} placeholder={label} /></label>)}</div></div><div className="address-card address-mail-card"><CardHeading icon={<Mail size={13} />} label="SOLICITAÇÃO DA EQUIPE" title="Modelo de e-mail — Mudança de Endereço" /><div className="address-mail-meta"><CopyField label="Para" value={PLANEJAMENTO_TO} copy={copy} copied={copied} /><CopyField label="CC" value={cc} copy={copy} copied={copied} /><CopyField label="Assunto" value={emailSubject} copy={copy} copied={copied} /></div><div className="address-document"><span>Documento que deve acompanhar o e-mail</span><strong><Paperclip size={14} /> Ofício.pdf</strong><p>Anexar o ofício recebido da escola ao e-mail antes do envio.</p></div><div className="address-before-send"><strong>ANTES DO ENVIO</strong><span>Confirmar que as evidências do novo endereço e a planta baixa estão disponíveis para serem anexadas ao e-mail.</span></div><pre>{emailBody}</pre><CopyButton label="COPIAR E-MAIL" copied={copied === 'email'} onClick={() => copy(fullEmail, 'email')} /><button className="address-body-copy" onClick={() => copy(emailBody, 'body')}><Copy size={14} /> Copiar corpo do e-mail</button></div><div className="responsibility-grid"><div><strong>RESPONSÁVEL PELA ESCOLA</strong><span>Fornecer informações, fotos, croqui/planta baixa, elaborar o ofício, enviá-lo aos destinatários e encaminhar cópia à equipe pelo WhatsApp.</span></div><div><strong>EQUIPE</strong><span>Confirmar a mudança, levantar informações, orientar a responsável, guardar o print no chamado, receber a cópia e realizar a solicitação.</span></div></div></div> }
function CopyField({ label, value, copy, copied }) { return <div className="address-copy-field"><span>{label}</span><div><code>{value}</code><button onClick={() => copy(value, label)}><Copy size={13} /></button></div>{copied === label && <small>Copiado!</small>}</div> }
